WILAYAH = {
    "Aceh": [
    "Kabupaten Aceh Barat",
    "Kabupaten Aceh Barat Daya",
    "Kabupaten Aceh Besar",
    "Kabupaten Aceh Jaya",
    "Kabupaten Aceh Selatan",
    "Kabupaten Aceh Singkil",
    "Kabupaten Aceh Tamiang",
    "Kabupaten Aceh Tengah",
    "Kabupaten Aceh Tenggara",
    "Kabupaten Aceh Timur",
    "Kabupaten Aceh Utara",
    "Kabupaten Bener Meriah",
    "Kabupaten Bireuen",
    "Kabupaten Gayo Lues",
    "Kabupaten Nagan Raya",
    "Kabupaten Pidie",
    "Kabupaten Pidie Jaya",
    "Kabupaten Simeulue",
    "Kota Banda Aceh",
    "Kota Langsa",
    "Kota Lhokseumawe",
    "Kota Sabang",
    "Kota Subulussalam"
  ],

  "Sumatera Utara": [
    "Kabupaten Asahan",
    "Kabupaten Batubara",
    "Kabupaten Dairi",
    "Kabupaten Deli Serdang",
    "Kabupaten Humbang Hasundutan",
    "Kabupaten Karo",
    "Kabupaten Labuhanbatu",
    "Kabupaten Labuhanbatu Selatan",
    "Kabupaten Labuhanbatu Utara",
    "Kabupaten Langkat",
    "Kabupaten Mandailing Natal",
    "Kabupaten Nias",
    "Kabupaten Nias Barat",
    "Kabupaten Nias Selatan",
    "Kabupaten Nias Utara",
    "Kabupaten Padang Lawas",
    "Kabupaten Padang Lawas Utara",
    "Kabupaten Pakpak Bharat",
    "Kabupaten Samosir",
    "Kabupaten Serdang Bedagai",
    "Kabupaten Simalungun",
    "Kabupaten Tapanuli Selatan",
    "Kabupaten Tapanuli Tengah",
    "Kabupaten Tapanuli Utara",
    "Kabupaten Toba",
    "Kota Binjai",
    "Kota Gunungsitoli",
    "Kota Medan",
    "Kota Padangsidimpuan",
    "Kota Pematangsiantar",
    "Kota Sibolga",
    "Kota Tanjungbalai",
    "Kota Tebing Tinggi"
  ],

  "Sumatera Barat": [
    "Kabupaten Agam",
    "Kabupaten Dharmasraya",
    "Kabupaten Kepulauan Mentawai",
    "Kabupaten Lima Puluh Kota",
    "Kabupaten Padang Pariaman",
    "Kabupaten Pasaman",
    "Kabupaten Pasaman Barat",
    "Kabupaten Pesisir Selatan",
    "Kabupaten Sijunjung",
    "Kabupaten Solok",
    "Kabupaten Solok Selatan",
    "Kabupaten Tanah Datar",
    "Kota Bukittinggi",
    "Kota Padang",
    "Kota Padang Panjang",
    "Kota Pariaman",
    "Kota Payakumbuh",
    "Kota Sawahlunto",
    "Kota Solok"
  ],

  "Riau": [
    "Kabupaten Bengkalis",
    "Kabupaten Indragiri Hilir",
    "Kabupaten Indragiri Hulu",
    "Kabupaten Kampar",
    "Kabupaten Kepulauan Meranti",
    "Kabupaten Kuantan Singingi",
    "Kabupaten Pelalawan",
    "Kabupaten Rokan Hilir",
    "Kabupaten Rokan Hulu",
    "Kabupaten Siak",
    "Kota Dumai",
    "Kota Pekanbaru"
  ],

  "Kepulauan Riau": [
    "Kabupaten Bintan",
    "Kabupaten Karimun",
    "Kabupaten Kepulauan Anambas",
    "Kabupaten Lingga",
    "Kabupaten Natuna",
    "Kota Batam",
    "Kota Tanjungpinang"
  ],

  "Jambi": [
    "Kabupaten Batanghari",
    "Kabupaten Bungo",
    "Kabupaten Kerinci",
    "Kabupaten Merangin",
    "Kabupaten Muaro Jambi",
    "Kabupaten Sarolangun",
    "Kabupaten Tanjung Jabung Barat",
    "Kabupaten Tanjung Jabung Timur",
    "Kabupaten Tebo",
    "Kota Jambi",
    "Kota Sungai Penuh"
  ],

  "Sumatera Selatan": [
    "Kabupaten Banyuasin",
    "Kabupaten Empat Lawang",
    "Kabupaten Lahat",
    "Kabupaten Muara Enim",
    "Kabupaten Musi Banyuasin",
    "Kabupaten Musi Rawas",
    "Kabupaten Musi Rawas Utara",
    "Kabupaten Ogan Ilir",
    "Kabupaten Ogan Komering Ilir",
    "Kabupaten Ogan Komering Ulu",
    "Kabupaten Ogan Komering Ulu Selatan",
    "Kabupaten Ogan Komering Ulu Timur",
    "Kabupaten Penukal Abab Lematang Ilir",
    "Kota Lubuklinggau",
    "Kota Pagar Alam",
    "Kota Palembang",
    "Kota Prabumulih"
  ],

  "Bengkulu": [
    "Kabupaten Bengkulu Selatan",
    "Kabupaten Bengkulu Tengah",
    "Kabupaten Bengkulu Utara",
    "Kabupaten Kaur",
    "Kabupaten Kepahiang",
    "Kabupaten Lebong",
    "Kabupaten Mukomuko",
    "Kabupaten Rejang Lebong",
    "Kabupaten Seluma",
    "Kota Bengkulu"
  ],

  "Lampung": [
    "Kabupaten Lampung Barat",
    "Kabupaten Lampung Selatan",
    "Kabupaten Lampung Tengah",
    "Kabupaten Lampung Timur",
    "Kabupaten Lampung Utara",
    "Kabupaten Mesuji",
    "Kabupaten Pesawaran",
    "Kabupaten Pesisir Barat",
    "Kabupaten Pringsewu",
    "Kabupaten Tanggamus",
    "Kabupaten Tulang Bawang",
    "Kabupaten Tulang Bawang Barat",
    "Kabupaten Way Kanan",
    "Kota Bandar Lampung",
    "Kota Metro"
  ],

  "Banten": [
    "Kabupaten Lebak",
    "Kabupaten Pandeglang",
    "Kabupaten Serang",
    "Kabupaten Tangerang",
    "Kota Cilegon",
    "Kota Serang",
    "Kota Tangerang",
    "Kota Tangerang Selatan"
  ],

  "DKI Jakarta": [
    "Kota Jakarta Barat",
    "Kota Jakarta Pusat",
    "Kota Jakarta Selatan",
    "Kota Jakarta Timur",
    "Kota Jakarta Utara",
    "Kabupaten Kepulauan Seribu"
  ],

  "Jawa Barat": [
    "Kabupaten Bandung",
    "Kabupaten Bandung Barat",
    "Kabupaten Bekasi",
    "Kabupaten Bogor",
    "Kabupaten Ciamis",
    "Kabupaten Cianjur",
    "Kabupaten Cirebon",
    "Kabupaten Garut",
    "Kabupaten Indramayu",
    "Kabupaten Karawang",
    "Kabupaten Kuningan",
    "Kabupaten Majalengka",
    "Kabupaten Pangandaran",
    "Kabupaten Purwakarta",
    "Kabupaten Subang",
    "Kabupaten Sukabumi",
    "Kabupaten Sumedang",
    "Kabupaten Tasikmalaya",
    "Kota Bandung",
    "Kota Banjar",
    "Kota Bekasi",
    "Kota Bogor",
    "Kota Cimahi",
    "Kota Cirebon",
    "Kota Depok",
    "Kota Sukabumi",
    "Kota Tasikmalaya"
  ],

  "Jawa Tengah": [
    "Kabupaten Banjarnegara",
    "Kabupaten Banyumas",
    "Kabupaten Batang",
    "Kabupaten Blora",
    "Kabupaten Boyolali",
    "Kabupaten Brebes",
    "Kabupaten Cilacap",
    "Kabupaten Demak",
    "Kabupaten Grobogan",
    "Kabupaten Jepara",
    "Kabupaten Karanganyar",
    "Kabupaten Kebumen",
    "Kabupaten Kendal",
    "Kabupaten Klaten",
    "Kabupaten Kudus",
    "Kabupaten Magelang",
    "Kabupaten Pati",
    "Kabupaten Pekalongan",
    "Kabupaten Pemalang",
    "Kabupaten Purbalingga",
    "Kabupaten Purworejo",
    "Kabupaten Rembang",
    "Kabupaten Semarang",
    "Kabupaten Sragen",
    "Kabupaten Sukoharjo",
    "Kabupaten Tegal",
    "Kabupaten Temanggung",
    "Kabupaten Wonogiri",
    "Kabupaten Wonosobo",
    "Kota Magelang",
    "Kota Pekalongan",
    "Kota Salatiga",
    "Kota Semarang",
    "Kota Surakarta",
    "Kota Tegal"
  ],

  "DI Yogyakarta": [
    "Kabupaten Bantul",
    "Kabupaten Gunungkidul",
    "Kabupaten Kulon Progo",
    "Kabupaten Sleman",
    "Kota Yogyakarta"
  ],

  "Jawa Timur": [
    "Kabupaten Bangkalan",
    "Kabupaten Banyuwangi",
    "Kabupaten Blitar",
    "Kabupaten Bojonegoro",
    "Kabupaten Bondowoso",
    "Kabupaten Gresik",
    "Kabupaten Jember",
    "Kabupaten Jombang",
    "Kabupaten Kediri",
    "Kabupaten Lamongan",
    "Kabupaten Lumajang",
    "Kabupaten Madiun",
    "Kabupaten Magetan",
    "Kabupaten Malang",
    "Kabupaten Mojokerto",
    "Kabupaten Nganjuk",
    "Kabupaten Ngawi",
    "Kabupaten Pacitan",
    "Kabupaten Pamekasan",
    "Kabupaten Pasuruan",
    "Kabupaten Ponorogo",
    "Kabupaten Probolinggo",
    "Kabupaten Sampang",
    "Kabupaten Sidoarjo",
    "Kabupaten Situbondo",
    "Kabupaten Sumenep",
    "Kabupaten Trenggalek",
    "Kabupaten Tuban",
    "Kabupaten Tulungagung",
    "Kota Batu",
    "Kota Blitar",
    "Kota Kediri",
    "Kota Madiun",
    "Kota Malang",
    "Kota Mojokerto",
    "Kota Pasuruan",
    "Kota Probolinggo",
    "Kota Surabaya"
  ],

  "Bali": [
    "Kabupaten Badung",
    "Kabupaten Bangli",
    "Kabupaten Buleleng",
    "Kabupaten Gianyar",
    "Kabupaten Jembrana",
    "Kabupaten Karangasem",
    "Kabupaten Klungkung",
    "Kabupaten Tabanan",
    "Kota Denpasar"
  ],

  "Nusa Tenggara Barat": [
    "Kabupaten Bima",
    "Kabupaten Dompu",
    "Kabupaten Lombok Barat",
    "Kabupaten Lombok Tengah",
    "Kabupaten Lombok Timur",
    "Kabupaten Lombok Utara",
    "Kabupaten Sumbawa",
    "Kabupaten Sumbawa Barat",
    "Kota Bima",
    "Kota Mataram"
  ],

  "Nusa Tenggara Timur": [
    "Kabupaten Alor",
    "Kabupaten Belu",
    "Kabupaten Ende",
    "Kabupaten Flores Timur",
    "Kabupaten Kupang",
    "Kabupaten Lembata",
    "Kabupaten Manggarai",
    "Kabupaten Manggarai Barat",
    "Kabupaten Manggarai Timur",
    "Kabupaten Nagekeo",
    "Kabupaten Ngada",
    "Kabupaten Rote Ndao",
    "Kabupaten Sabu Raijua",
    "Kabupaten Sikka",
    "Kabupaten Timor Tengah Selatan",
    "Kabupaten Timor Tengah Utara",
    "Kota Kupang"
  ]
}
